server:
  port: 9000

# spring boot
spring:
  application:
    name: peizhi
    cloud:
      config:
        server:
          git:
            uri: http://192.168.0.202/avic/configfiles.git
            searchPaths:
              - common
              - database
              - services
              - thirdpart
            username: jiqiren
            password: pa$$word

# logging
logging:
  file: log/peizhi.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd}) %clr(%d{HH:mm:ss}){cyan}.%clr(%d{SSS}){blue} %clr(%.-1level) %clr(|){magenta} %-200.-200msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%thread] %logger | %msg%n"
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
