server:
  port: 8080

# spring boot
spring:
  application:
    name: peizhi
  cloud:
    config:
      server:
        git:
          uri: http://192.168.0.202/avic/configfiles.git
          searchPaths:
            - common
            - database
            - services
          username: jiqiren
          password: pa$$word

# logging
logging:
  file: log/peizhi.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd}){cyan} %clr(%d{HH:mm:ss.SSS}){blue} %clr(%-5level) %clr(|){magenta} %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%thread] %logger{15} | %msg%n"
  level:
    root: INFO
    com.avic.mti.peizhi: TRACE
    org.springframework.web: DEBUG
    org.hibernate: ERROR
