server:
  port: 9000

# spring boot
spring:
  application:
    name: peizhi
  cloud:
    config:
      server:
        git:
          uri: file:///app/git
          searchPaths:
            - common
            - database
            - services

# logging
logging:
  file: log/peizhi.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd}) %clr(%d{HH:mm:ss}){cyan}.%clr(%d{SSS}){blue} %clr(%.-1level) %clr(|){magenta} %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%thread] %logger | %msg%n"
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
