server:
  port: 8080

# spring boot
spring:
  application:
    name: peizhi
  profiles:
    active: default
  main:
    banner-mode: "console"
  jackson:
    time-zone: Asia/Shanghai
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  cloud:
    config:
      uri: http://localhost:8080
      server:
        git:
          uri: http://192.168.0.202/avic/configfiles.git
          search-paths: services
          username: jiqiren
          password: pa$$word

# logging
logging:
  group:
    app: com.avic.mti.peizhi
    spring: org.springframework
  pattern:
    console: "%clr(%d{yyyyMMdd.HHmmss.SSS}){cyan} %clr(%5p): %msg%n"
  level:
    root: INFO
    app: TRACE
  file: log/peizhi.log
