server:
  port: 8080

# spring boot
spring:
  application:
    name: peizhi
  cloud:
    config:
      server:
        git:
          uri: http://192.168.0.202/avic/configfiles.git
          searchPaths:
            - common
            - database
            - services
          username: jiqiren
          password: pa$$word

# logging
logging:
  file: log/peizhi.log
  group:
    app: com.avic.mti.peizhi
  pattern:
    dateformat: "yyyyMMdd.HHmmss.SSS"
    console: "%clr(%d){cyan} %clr(%5p): %msg%n"
    file: "%d %5p: %msg%n"
  level:
    root: INFO
    app: TRACE
