# spring boot
spring:
  main:
    banner-mode: "console"
  jackson:
    time-zone: Asia/Shanghai
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  cloud:
    config:
      server:
        git:
          uri: http://192.168.0.202/avic/configfiles
          searchPaths: services
          username: jiqiren
          password: pa$$word

# logging
logging:
  group:
    app: com.avic.mti.peizhi
    spring: org.springframework
  pattern:
    console: "%clr(%d{yyyyMMdd.HHmmss.SSS}){cyan} %clr(%5p): %msg%n"
  level:
    root: INFO
    app: TRACE
    spring: ERROR
    sql: WARN
    web: DEBUG
  file: log/peizhi.log
